# Generated by Django 4.0.10 on 2023-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
