# Generated by Django 4.0.10 on 2023-06-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_exeducation_experice_resume_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExEducation',
            new_name='Education',
        ),
        migrations.RenameModel(
            old_name='Experice',
            new_name='Experience',
        ),
    ]
