# Generated by Django 4.0.10 on 2023-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_exeducation_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(),
        ),
    ]
