# Generated by Django 4.0.10 on 2023-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_education_from_date_alter_education_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(null=True, upload_to='resume/images/'),
        ),
    ]
