# Generated by Django 4.0.10 on 2023-06-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_contactmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessages',
            old_name='phone',
            new_name='subject',
        ),
    ]
