# Generated by Django 4.0.10 on 2023-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_phone_contactmessages_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.PositiveBigIntegerField()),
                ('projects', models.PositiveBigIntegerField()),
                ('coffee', models.PositiveBigIntegerField()),
            ],
        ),
    ]
