# Generated by Django 4.0.10 on 2023-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_achivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='fb_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='github_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
