# Generated by Django 4.0.10 on 2023-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_resume_fb_link_resume_github_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=300)),
                ('web_cat', models.CharField(max_length=300)),
                ('features', models.CharField(max_length=300)),
            ],
        ),
    ]
